#!/usr/bin/env bash
# NEEDLE CLI Configuration Management
# Load, validate, and manage configuration

# Check if NEEDLE is initialized
_needle_is_initialized() {
    [[ -f "$NEEDLE_HOME/$NEEDLE_CONFIG_FILE" ]]
}

# Get config value (simple YAML key extraction)
_needle_config_get() {
    local key="$1"
    local config_file="$NEEDLE_HOME/$NEEDLE_CONFIG_FILE"

    if [[ ! -f "$config_file" ]]; then
        return 1
    fi

    # Simple extraction for top-level keys (no nested objects)
    grep -E "^${key}:" "$config_file" 2>/dev/null | sed 's/^[^:]*: *//' | sed 's/^"//' | sed 's/"$//'
}

# Set config value (simple YAML key setting)
_needle_config_set() {
    local key="$1"
    local value="$2"
    local config_file="$NEEDLE_HOME/$NEEDLE_CONFIG_FILE"

    if [[ ! -f "$config_file" ]]; then
        return 1
    fi

    # Simple replacement for top-level keys
    if grep -q "^${key}:" "$config_file" 2>/dev/null; then
        # Use different separator to avoid issues with paths
        sed -i "s|^${key}:.*|${key}: ${value}|" "$config_file"
    else
        echo "${key}: ${value}" >> "$config_file"
    fi
}

# Create default configuration
_needle_config_create_default() {
    local config_file="$1"

    cat > "$config_file" << 'EOF'
# NEEDLE Configuration
# Generated by needle init

# General settings
editor: "${EDITOR:-vim}"
timezone: "UTC"

# Execution settings
timeout: 300
parallel: true
max_workers: 4

# Logging
log_level: "info"
log_retention_days: 30

# Feature flags
experimental: false
EOF
}

# Validate configuration
_needle_config_validate() {
    local config_file="$NEEDLE_HOME/$NEEDLE_CONFIG_FILE"

    if [[ ! -f "$config_file" ]]; then
        _needle_error "Configuration file not found: $config_file"
        return 1
    fi

    # Add validation logic here as needed
    return 0
}
